// surveyjs/survey-library/packages/survey-react-ui/src/components/action-bar/action-bar-item-dropdown.tsx
import React from "react";
import { ActionDropdownViewModel, getActionDropdownButtonTarget } from "survey-core";
import { ReactElementFactory } from "../../element-factory";
import { Popup } from "../popup/popup";
import { SurveyActionBarItem } from "./action-bar-item";

export class SurveyActionBarItemDropdown extends SurveyActionBarItem {
  private viewModel: ActionDropdownViewModel;
  constructor(props: any) {
    super(props);
  }
  renderInnerButton() {
    const button = super.renderInnerButton();
    return (
      <>
        {button}
        <Popup model={this.item.popupModel}></Popup>
      </>
    );
  }
  componentDidMount(): void {
    this.viewModel = new ActionDropdownViewModel(this.item);
  }
  componentWillUnmount(): void {
    super.componentWillUnmount();
    this.viewModel.dispose();
  }
}

ReactElementFactory.Instance.registerElement("sv-action-bar-item-dropdown", (props) => {
  return React.createElement(SurveyActionBarItemDropdown, props);
});

// surveyjs/survey-library/src/vue/components/action-bar/action-bar-item-dropdown.vue
<template>
  <div style="width: 100%">
    <button
      type="button"
      :class="item.getActionBarItemCss()"
      v-on:click="
        (args) => {
          item.action(item, !!args.pointerType);
        }
      "
      v-on:keyup="
        (evt) => {
          evt.stopPropagation();
        }
      "
      v-bind:disabled="item.disabled"
      v-bind:title="item.tooltip || item.title"
      v-bind:role="item.ariaRole"
      v-bind:tabindex="item.disableTabStop ? -1 : 0"
      v-key2click="{ processEsc: false, disableTabStop: item.disableTabStop }"
    >
      <sv-svg-icon
        v-if="item.iconName"
        :class="item.cssClasses.itemIcon"
        :iconName="item.iconName"
        :size="item.iconSize"
        :title="item.tooltip || item.title"
      ></sv-svg-icon>

      <span
        v-if="item.hasTitle"
        :class="item.getActionBarItemTitleCss()"
        >{{ item.title }}</span
      >
    </button>
    <sv-popup
      :model="item.popupModel"></sv-popup>
  </div>
</template>

<script lang="ts">
import { Component } from "vue-property-decorator";
import Vue from "vue";
import ActionBarItemViewModel from "./action-bar-item.vue";
import { ActionDropdownViewModel, getActionDropdownButtonTarget } from "survey-core";

@Component
export class ActionBarItemDropdownViewModel extends ActionBarItemViewModel {
  private viewModel: ActionDropdownViewModel;
  constructor() {
    super();
    this.viewModel = new ActionDropdownViewModel(this.item);
  }
  onDestroyed() {
    this.viewModel.dispose();
  }
}
Vue.component("sv-action-bar-item-dropdown", ActionBarItemDropdownViewModel);
export default ActionBarItemDropdownViewModel;
</script>
